### ISSUE TITLE
Suggestions for fastq benchmark

### ISSUE THREAD

**Issue by mbhall88** [lh3/biofast#1]
Sorry if I have jumped the gun here and these suggestions are forthcoming. These would be the two libraries I use most (and I suspect quite a few other do too) for the respective languages. I'm interested to see where they fall in the existing benchmark.

- Python [`pysam.FastxFile`](https://pysam.readthedocs.io/en/latest/api.html#pysam.FastxFile) from [pysam][pysam].
- Rust [`bio::io::fastq::Reader`](https://docs.rs/bio/0.30.1/bio/io/fastq/struct.Reader.html) from the [rust-bio][rust] library

Not sure if this is also of interest, but [hyperfine][hyperfine] is a nice tool for doing this kind of benchmarking. Not only will it give relative times with multiple runs, but also allows for warm-up runs (useful for IO intensive processes). I've used it for a very similar task [here](https://github.com/mbhall88/rasusa#benchmark).

**EDIT:**  
Just read the accompanying blog again and noticed you mentioned you implemented in languages you are familiar with. I'm happy to provide any Rust examples if needed.

[pysam]: https://pysam.readthedocs.io/en/latest/
[rust-bio]: https://rust-bio.github.io/
[hyperfine]: https://github.com/sharkdp/hyperfine

**Comment by lh3** [comment]
Thanks for hyperfine. I should probably learn to use that.

This repo focuses "high-level" languages that biologists may use. I doubt biologists would choose rust, java, go, etc, so I didn't include them. That said, if someone wants to provide implementations in these languages, I can try and add the results to the table.

I don't know pysam.FastxFile (well, I rarely use python). Is it another kseq.h binding or a python implementation?

**Comment by nh13** [comment]
I haven't seen too many biologists using `Javascript`, `Julia`, and `LuaJIT`, but that could me and my bias (and the clients I work with).  Also, not many biologists using `C` but I assume that's for a benchmark.  So I don't buy it.  But that being said, I was thinking of making a PR or two for a few other languages that I've seen folks use, so I'd be open to adding them.  We could also use github actions to run the perf benchmark.

**Comment by lh3** [comment]
Julia is <2 years old. Nim is 0.5 year old. Crystal is unborn yet. I don't expect biologists to use them right now. C is in the mix only to set a base line. My blog post is more about the potential future in several years. Note that I am not putting a "high-level" label on this repo, so implementations in any languages are welcomed.

**Comment by chris-rands** [comment]
Are all the python timings using CPython? I would be interested to see timings with PyPy (which is supported by Biopython)

**Comment by cjw85** [comment]
I don't know much about the scope of what PyPy can JIT compile but if you lineprofile the pyfastx example, half the time is spent in the accumulation of the sequence lengths. With respect to the C baseline, the test is as much about python's ability to perform dynamic dispatch to add integers as it is measuring the overhead of forming python objects out of the kseq.h structs.

```Total time: 15.3851 s
File: fastx.py
Function: main at line 28

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    28                                           @profile
    29                                           def main():
    30         1         21.0     21.0      0.0      n, slen, qlen = 0, 0, 0
    31   5682011    7366975.0      1.3     47.9      for name, seq, qual in pyfastx.Fastq(sys.argv[1], build_index=False):
    32   5682010    2324629.0      0.4     15.1          n += 1
    33   5682010    2783887.0      0.5     18.1          slen += len(seq)
    34   5682010    2909447.0      0.5     18.9          qlen += qual and len(qual) or 0
    35         1        158.0    158.0      0.0      print('{}\t{}\t{}'.format(n, slen, qlen))
```

@lh3 Yes, pysam.FastxFile using kseq.h. ([libcfaidx.pxd](https://github.com/pysam-developers/pysam/blob/aa27e81b123067427ae08f5345feb891b7efa857/pysam/libcfaidx.pxd))

**Comment by mbhall88** [comment]
> This repo focuses "high-level" languages that biologists may use. I doubt biologists would choose rust, java, go, etc, so I didn't include them. That said, if someone wants to provide implementations in these languages, I can try and add the results to the table.

I guess that depends on your definition of biologist (which is a grey area these days admittedly). But I agree that for tasks where I am wanting to look at thing's "quick-and-dirty" I would use Jave/Rust/C++ etc. However, if speed/memory is important I am now doing everything in Rust (moved from C++ recently) as I find this is a great bridge between C and Python in terms of speed, memory, and ease of use (i.e. syntax, compiling etc.). Anyway, I'm just rambling now...

> I don't know pysam.FastxFile (well, I rarely use python). Is it another kseq.h binding or a python implementation?

Yes, pysam is using htslib, which I assume is, itself, using kseq.h

**Comment by lostmsu** [comment]
> potential future in several years

Then not trying high-level languages from the top of TIOBE does not make much sense.

**Comment by chris-rands** [comment]
From a quick test, using PyPy is ~3 times faster than using CPython for the Biopython script (other Python parsers may also be faster). @lh3 would you consider adding PyPy timings to this repo?

CPython:
```
$ time python3 fqcnt_py3.6_bp.py biofast-data-v1/M_abscessus_HiSeq.fq 
3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0]
CPython
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.7.1908-Core
1.76
5682010	568201000	568201000

real	3m34.855s
user	3m31.050s
sys	0m2.421s
```

PyPy:
```
$ time pypy3 fqcnt_py3.6_bp.py biofast-data-v1/M_abscessus_HiSeq.fq 
3.6.9 (?, Apr 10 2020, 19:47:05)
[PyPy 7.3.1 with GCC 7.3.0]
PyPy
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.7.1908-Core
1.76
5682010	568201000	568201000

real	1m13.458s
user	1m11.295s
sys	0m1.364s
```

Script:
```
$ cat fqcnt_py3.6_bp.py 
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

if __name__ == "__main__":
    from Bio import SeqIO
    import sys, re, gzip
    if len(sys.argv) == 1:
        print("Usage: fqcnt.py <in.fq.gz>")
        sys.exit(0)
    fn = sys.argv[1]
    if re.search(r'\.gz$', fn):
        fp = gzip.open(fn, 'rt')
    else:
        fp = open(fn, 'r')
    n, slen = 0, 0
    for seq in SeqIO.parse(fp, "fastq"):
        n += 1
        slen += len(seq)
    print('{}\t{}\t{}'.format(n, slen, slen))
```

**Comment by lh3** [comment]
I am closing this issue as multiple related PRs have been merged.
