### ISSUE TITLE
Benchmarks do not run for long enough; too biased by non-reading code performance

### ISSUE THREAD

**Issue by nh13** [lh3/biofast#13]
The benchmarks run only for a few seconds to under a minute.  If a certain language takes a while to start and/or shutdown is REPL or JVM, has code outside the reading/writing of the FASTQ that are slow (ex. Java reflection for arg-parsing), then the benchmarks speed are more indicative of that then the core part we care about (reading FASTQs).  [In your own words:](https://discourse.julialang.org/t/lhe-biofast-benchmark-fastq-parsing-julia-nim-crystal-python/39747/20)
> When you read through a 100Gb gzip’d fastq file, performance matters. 30min vs 1hr is a huge difference. High-performance tools often put fastq reading in a separate thread because it is too slow. Zlib is the main bottleneck here, but parsing time should be minimized as well.

A few things can be done to isolate the reading/writing code:
1. Run a benchmark with a single FASTQ read/record.  This has the downfall if the reading code has some start/shutdown time, it is included in the total time.
2. Run a benchmark on a 100Gb gzip'd fastq file as you mention about.  This could also be something suitably large such that 5-20s overhead can be either be removed using the value from (1), or just be included because it's negligible over a 30m run time.

Related to: https://github.com/lh3/biofast/pull/5

**Comment by lh3** [comment]
Not everyone is working with human data. The test data file gives >100-fold coverage for a bacterial genome. For real datasets at this scale, startup time matters. Long startup time is a weakness and should get penalized.

In addition, I don't have the bandwidth to run these tools on much larger datasets. Even the fastest implementation would take several hours with hyperfine.

**Comment by nh13** [comment]
@lh3 
> In addition, I don't have the bandwidth to run these tools on much larger datasets. Even the fastest implementation would take several hours with hyperfine.

I am sure folks can help.  For example, I could spin up an ec2 instance each week to update the benchmarks on a big dataset for those implementations that have been added or changed.

At least add a disclaimer in the README, since this benchmark will likely get treated as gospel since folks value your opinion highly.  They don't consider the nuances or limitations of the benchmark (aka. times where startup time doesn't matter like the _100gb fastq benchmark you argued for elsewhere!_)
